#-------------------------------
# General Site Settings
title: Bumi.log
logo: /images/logo2.png # You can add own logo. For example '/images/logo.png'.
description: Hi, I'm Bumi Kim. I'm a UX designer based in Korea. I also write code for web design, 3d render and animation.
baseurl: "/blog" # The subpath of your site, e.g. /blog
url: "https://bumikim.netlify.app" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author-name: Bumi Kim

#-------------------------------
# Hero Settings
hero:
  image: '/images/heroimg.jpg'
  title: Bumi Kim #Nick Adams
  description: a UX designer #Thoughts, stories and ideas.

social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/bumi-kim/"}
- {icon: "ion-logo-github", link: "https://github.com/kimbumi"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/channel/UCfgkLZpQJB0mxIP5SgsNNhg/channels"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/bumikimm/"}

# Example of adding a new link to the author section and footer - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: bumikim26@gmail.com # Add your email for contact form
  description: Let's talk! I'd love to hear from you about any question or projects. Cheers! # Add a description of your form

# NOTE
# Sanara comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: bumikim # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: true # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
mailchimp-title: Get new post # Add your title.
mailchimp-text: Subscribe to my blog and you can get the emails of latest posts! # Add your description.
mailchimp-identifier: https://us1.admin.mailchimp.com/lists/settings/defaults?id=1654882 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed